### ISSUE TITLE
Poetry build will not write version inside __init__.py or __version__.py

### ISSUE THREAD

**Issue by goldstein0101** [mtkennerly/poetry-dynamic-versioning#104]
Hey, im using simple example from README, but yet, version is not overwritten in toml or in __version__.py.
```
[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
full-commit = true

```

**Comment by goldstein0101** [comment]
1. poetry add poetry-dynamic-versioning[plugin]
2. Yeah, then my mistake, i tought it would change also the normal copy of project, but it does only to wheel/sdist.
3. Yes
4. Exactly

I just wanted to make changes in normal copy and inside pyproject.toml. Since i am also using those versions for deployment on some third party platform as a tag.And i am tagging it as my_package.__version__, thats why i wanted to have it in normal copy.

**Comment by mtkennerly** [comment]
Gotcha. To modify the normal copies, you can run `poetry dynamic-versioning` (note the space). It leaves the edits when it's done, so if your deployment workflow requires committing/tagging, then you can save the changes that way.

If possible, you might want to consider using `poetry build` and then deploying the sdist (`<repo>/dist/<project>-<version>.tar.gz`), but I understand that may not work with the third-party service you're using.

> poetry add poetry-dynamic-versioning[plugin]

You'll need to use `poetry self add` rather than `poetry add`. The former adds it globally to Poetry, and the latter adds it inside of your project's venv (which doesn't have access to plug into the global copy of Poetry).

> Bold means double score, sorry for bad writing

No worries :) You can wrap text in backticks ( ` , on the same key as ~) to avoid that.

**Comment by goldstein0101** [comment]
Thank u very much for answer, one more thing, i am looking into docs, and i dont see how to specify repository for poetry self,
since im using private repository(artifactory).

**Comment by mtkennerly** [comment]
Hmm, I'm not sure of the recommended way to do that. There's the [`poetry source add`](https://python-poetry.org/docs/repositories/) command, but I don't know if `poetry self add` respects it. I found a couple of Poetry tickets (https://github.com/python-poetry/poetry/issues/6528, https://github.com/python-poetry/poetry/issues/6529) that suggest it may not be directly supported, but they do mention some workarounds.

I think you could download from Artifactory as a separate step and then run `poetry self add '<name>.whl[plugin]'` on the downloaded plugin wheel. When I test the plugin locally, I build a wheel and install it, so that should work. It does complain if you delete the wheel without uninstalling the plugin, so just watch out for that.
