### ISSUE TITLE
Error when installing package with `pip install .`

### ISSUE THREAD

**Issue by GuillemGSubies** [mtkennerly/poetry-dynamic-versioning#118]
This is my pyproject:

```
[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
format = "{branch}"
```

I can install my package via poetry, but when I try to install with `pip install .` (poetry should be compatible with it) I get an error because the name of my branch does not follow semver. When I disable the poetry-dynamic-versioning, everything works fine.

Am I doing anything wrong?

The error:

```
      ValueError: Version 'doc-workflow' does not conform to the Semantic Versioning style
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Notice:  A new release of pip is available: 22.3.1 -> 23.1.1
Notice:  To update, run: pip install --upgrade pip
Error: Process completed with exit code 1.
```

**Comment by mtkennerly** [comment]
> I can install my package via poetry

Are you sure the plugin is properly installed alongside Poetry and that it was installed with the `[plugin]` feature? I just tested, and `poetry install` should produce an error like this: `Invalid PEP 440 version: 'branch-name'` (this is an error coming from Poetry itself, not form the plugin)

> Am I doing anything wrong?

Since your branch name isn't a valid version, you would need to add it in the metadata segment instead, such as:

```format = "{base}+{branch}"```

**Comment by GuillemGSubies** [comment]
Thank you very much for answering so quickly.

The thing is that when I disable `poetry-dynamic-versioning` I can install via pip so I think it must be working. The only place when I specify that I want to install `poetry-dynamic-versioning` is in `[build-system]`, should I do it elsewhere?

The solution you gave me for `format` would solve it. However I just want to run `poetry-dynamic-versioning` when the branch I'm in is a tag, otherwise the installation will be for testing in a local environment and I won't care about the name of the version. Is there a way to do that?

**Comment by mtkennerly** [comment]
> The thing is that when I disable poetry-dynamic-versioning I can install via pip so I think it must be working.

Right, what I meant is that `pip` is working as expected (the error is correct), but `poetry install` should also be failing. If `poetry install` is not failing, then the plugin probably isn't active when you're running Poetry commands.

Pip respects the `[build-system]` section, but Poetry does not. Poetry itself requires the plugin to be installed manually (e.g., `poetry self add "poetry-dynamic-versioning[plugin]"` - note that the `[plugin]` feature is required in this case).

> However I just want to run poetry-dynamic-versioning when the branch I'm in is a tag, otherwise the installation will be for testing in a local environment and I won't care about the name of the version. Is there a way to do that?

Well, the plugin needs to run in order to know if the commit is tagged in the first place, but you can format the version differently depending on that information. For example (distance == 0 means the commit is tagged):

```toml
format-jinja = "{% if distance == 0 %}{{ base }}{% else %}{{ base }}+{{ branch }}{% endif %}"
```

Even in a dev environment when you don't care about the version yet, I think it should be fine to let the dynamic versioning run anyway, though. Is it hurting anything?

**Comment by GuillemGSubies** [comment]
Ok I understand. Everything is working correctly right now. Thank you very much for everything 😊
