### ISSUE TITLE
cannot install plugin ..  Failed to clone https://github.com/python-poetry/poetry-plugin-bundle.git

### ISSUE THREAD

**Issue by matt-mercer** [mtkennerly/poetry-dynamic-versioning#131]
I'm getting an error attempting to install this plugin, 

"PoetryConsoleError

  Failed to clone https://github.com/python-poetry/poetry-plugin-bundle.git at 'c9c7a8c4ef74948236c68349f07f76a1de77205b', verify ref exists on remote."

running the command
poetry self add "poetry-dynamic-versioning[plugin]==0.24.0"

I'm getting this on multiple poetry versions .. have tried with poetry 1.3.2, 1.5.0 and 1.5.1

![image](https://github.com/mtkennerly/poetry-dynamic-versioning/assets/449892/55cc521f-b8a8-4abd-8946-5213af8e1c66)

seems like a dependency on an explicit git ref that no longer exists ..

**Comment by mtkennerly** [comment]
Hi! From the console output, poetry-dynamic-versioning (PDV) itself is installing successfully. poetry-plugin-bundle (PPB) is an unrelated plugin and is not a dependency of PDV.

PDV releases don't ship with a lockfile either, so that's probably referring to Poetry's internal pyproject.toml/poetry.lock files used for tracking installed plugins. You could try deleting those files (for me, on Windows, they're located in `%APPDATA%\pypoetry`), and then try reinstalling your plugins.

**Comment by matt-mercer** [comment]
thanks ... I'm installing poetry using asdf so I'll have to go and hunt for for the poetry  pyproject.toml

**Comment by matt-mercer** [comment]
ok .. no idea where poetry-plugin-bundle came from / pervades multiple poetry versions, but  for me running 
`poetry self remove poetry-plugin-bundle` against one seems to have resolved it (across all poetry versions) ..

**Comment by mtkennerly** [comment]
Definitely weird, but I'm glad you got it working 👍
