### ISSUE TITLE
Dynamic versioning via Github tags seems broken as of 0.24.0

### ISSUE THREAD

**Issue by agoblet** [mtkennerly/poetry-dynamic-versioning#136]
Dynamic versioning via Github tags seems broken as of 0.24.0. The package seems to fall back on the previous tag and ignore the new tag. We ran various combinations of tags and poetry-dynamic-versioning / dunamai versions in the past weeks, without changing anything else in our setup:

|poetry-dynamic-versioning version|dunamai version|tag on github|version built by poetry|working|
|---|---|---|---|---|
|0.23.0|1.17.0|v0.6.5dev1|0.6.5dev1|yes|
|0.24.0|1.17.0|v0.7.6|0.7.6|yes|
|0.25.0|1.18.0|v0.7.7|0.7.6|no|
|0.25.0|1.18.0|v0.7.7dev|0.7.6|no|
|0.25.0|1.18.0|v0.7.7dev1|0.7.6|no|
|0.24.0|1.18.0|v0.7.7dev1|0.7.6|no|
|0.24.0|1.17.0|v0.7.7dev2|0.7.6|no|
|0.23.0|1.17.0|v0.7.7dev3|0.7.7dev3|yes|

Is this intended behavior? Did something change about the version patterns by any chance? For now we are pinning to 0.23.0 / 1.17.0 to be safe.

**Comment by mtkennerly** [comment]
Hi! That's definitely not intentional, but none of the changes should have that effect. Certainly no change to the default tag pattern.

I do see that you have two rows for 0.24.0 + 1.17.0, where one worked and one didn't. That makes it seem like something else is going on.

Some questions:

* Is this a public project? If possible, I would be interested in seeing the workflow file and testing a fork.
* Are all of those rows using the same workflow trigger (e.g., tag push)? Any event differences like isolated push vs PR push vs PR merge?
* Are they all on the same branch, or are you using separate release branches?
* Are you using lightweight tags, annotated tags, or a mix of both?

**Comment by agoblet** [comment]
Hi there, thanks for the quick reply!

> I do see that you have two rows for 0.24.0 + 1.17.0, where one worked and one didn't. That makes it seem like something else is going on.

Yes that is indeed strange, that definitely needs more investigation. The only thing that seemed to be changed over the past weeks in our workflow was the dynamic versioning version (it would always use the latest). I'll run some more experiments to get more clarity on this.

Regarding your questions:
- private project unfortunately, so you cannot debug it yourself.
- all these rows are from the exact same workflow trigger indeed: release
    - no, all via release process in github
    - we do not create a tag as part of a PR, we create a tag on release creation
- they are not all on the same branch. Most are on main, while the dev releases are usually on feature branches
- tags are created by the github release process, I think they are lightweight

**Comment by agoblet** [comment]
Did another run with the latest versions of poetry-dynamic-versioning and dunamai and that worked just fine. So likely something else is going on here indeed. Maybe something caching related in github workflows. Downgrading your packages was probably a coincidental fix. Will close this issue, thanks for you help and sorry for the false alarm 😬

**Comment by mtkennerly** [comment]
No worries! If the release process is parallelized, maybe there's a race condition between creating the tag and running the versioning step?

**Comment by agoblet** [comment]
that could be the case, since the workflow is triggered on release rather than on tag-push
