### ISSUE TITLE
Handle 'no previous tag' case

### ISSUE THREAD

**Issue by gsemet** [mtkennerly/poetry-dynamic-versioning#15]
Hi,

When there are no previous tag yet on a project, the jinja rendering gets a `distance=0` so it always displays "0.0.0".

My recommendation is to get a distance = number of total commit since initial commit so that the versions will be 0.0.1.dev1, 0.0.1.dev2, 0.0.1.dev3...

**Comment by mtkennerly** [comment]
Thanks for the feedback! I think your suggestion makes sense. My original thinking was that, if there's no tag, then there can't be any distance from a tag logically - but since 0.0.0 acts like an imaginary tag for the first commit, it does make sense to have a distance relative to it, especially if you don't create any tags for a while in a new repo.

The distance calculation comes from [Dunamai](https://github.com/mtkennerly/dunamai), so I'll make the change there.

**Comment by mtkennerly** [comment]
This behavior is now implemented in [Dunamai v1.3.0](https://github.com/mtkennerly/dunamai/releases/tag/v1.3.0). If you update the installed version of Dunamai, then poetry-dynamic-versioning will automatically use it.
