### ISSUE TITLE
How to get poetry version at runtime?

### ISSUE THREAD

**Issue by andreaskoelsch** [mtkennerly/poetry-dynamic-versioning#195]
When I `poetry install` my package with enabled poetry-dynamic-versioning plugin, it gets the current number which is fine. However, when I develop further, `poetry version` always shows me the current dynamic version number while ` python -c "from importlib.metadata import version; print(version('mypackage'))` still displays the version number from the installation.

Sometimes, it's useful to know the current version number of the package at runtime. Is this supported with this plugin? My current (ugly) workaround is to call `poetry version` in a subprocess

**Comment by mtkennerly** [comment]
Hi! By default, this plugin makes sure that the version is available for end users when they install or run your package (by injecting a static copy of the version into the wheel/sdist), but doesn't make the version available locally during development. Just to be clear, `importlib.metadata` would work fine for an end user, just not in a dev setup.

If you really need to read the current version during development, then I think your workaround with `poetry version`  is okay, as long as you gate it so that it doesn't happen on an end user installation.

**Comment by edgarrmondragon** [comment]
fwiw running that short script in the venv managed by poetry should get you the dynamic version after a `poetry install`:

```console
$ poetry run python -c "from importlib.metadata import version; print(version('mypackage'))
0.41.0a1.post2.dev0+170f5bc5
```

**Comment by andreaskoelsch** [comment]
@mtkennerly how could I gate such a function to know whether it's dev or not? 

@edgarrmondragon afaict, you just repeated my initial solution.

**Comment by mtkennerly** [comment]
A simple option would be to check for an environment variable like `MY_PROJECT_DEV_MODE=1`.

**Comment by andreaskoelsch** [comment]
thanks, that's probably good enough
