### ISSUE TITLE
How to make dev release auto-bump patch?

### ISSUE THREAD

**Issue by fredrikaverpil** [mtkennerly/poetry-dynamic-versioning#20]
Let's say a commit is tagged with 1.0.0. Then I create another commit without tagging it. Now, how can I make my builds say 1.0.1.dev0... by default (like setuptools_scm does) until I actually create another git tag?

I am just wondering about the automatic patch bump, like assuming that the next tag will _at least_ be a patch bump (but since no tagging was made, you don't really know).

**Comment by mtkennerly** [comment]
You can use the `bump_version` function to do this, which takes the base version and the index to bump:

```toml
[tool.poetry-dynamic-versioning]
enable = true
format-jinja = """
    {%- if distance == 0 -%}
        {{- base -}}
    {%- else -%}
        {{- bump_version(base, 2) }}.dev{{ distance - 1 }}+g{{ commit }}.d{{ datetime.now().strftime('%Y%m%d%H%M%S') -}}
    {%- endif -%}
"""
format-jinja-imports = [
    { module = "datetime", item = "datetime" }
]
```

When the default version is `0.8.3.post1.dev0+1d9637d`, the above will produce `0.8.4.dev0+g1d9637d.d20200827150727`.

Note that I used `distance - 1` in order to produce `dev0` instead of `dev1`.

**Comment by fredrikaverpil** [comment]
Ooh, excellent :) Thank you so much.
