### ISSUE TITLE
PEP 517 clarification

### ISSUE THREAD

**Issue by jhrmnn** [mtkennerly/poetry-dynamic-versioning#38]
The README says

> Include the plugin in the build-system section of pyproject.toml for interoperability with PEP 517 build frontends.

I did that, but then installing the created source distribution `poetry build -f sdist` with Pip fails, because Pip tries to first build the wheel, so it installs all build dependencies, and this then crashes with
```
RuntimeError: Unable to detect version control system.
```
When I don't include the plugin in the build-system dependencies, then everything actually works just fine. Am I missing something?

**Comment by mtkennerly** [comment]
Unfortunately, you're not missing anything. This is covered in the `caveats` section of the README. Pip creates an isolated copy of the source code, without the Git history, so there's no way for the plugin to find out the version.

However, following the PEP 517 interoperability note does mean that your project can be built through Pip when it's a Git dependency of another project, since in that case the Git history would be included.

**Comment by jhrmnn** [comment]
Could this be solved be an option that would cause the plugin to detect and set the version from VCS *only* when the version in `pyproject.toml` is set to, say, `'0.0.0'`?

**Comment by jhrmnn** [comment]
I just realized that `pyproject.toml` is only copied to the source distribution, ao it has the VCS version label. But maybe the plugin could look for the version label in `setup.py`, which is generated.

**Comment by mtkennerly** [comment]
Hmm, I didn't necessarily think there was a setup.py generated in PEP 517 mode, or at least I don't see one in the wheel created by `pip wheel .`. I think Pip copies the files it wants for the build to a temporary directory first, and only then activates the configured `build-system`, so the plugin doesn't even know which directory you were in when you ran the Pip command in order to check the VCS info that way.

This issue is related, but hasn't had activity for a while: https://github.com/pypa/pip/issues/5519

**Comment by jhrmnn** [comment]
There isn't. But that's not a problem, because if you already install a wheel, then there is no PEP 517 mode in play, so all this doesn't matter. I was speaking about the source distribution generated by Poetry (`poetry build -f sdist`), which, when installed, triggers the PEP 517 build. And Poetry includes `setup.py` in there, I assume for compatibility with pre-PEP 517 era.

And I was actually wrong above, `pyproject.toml` is not copied over, but built by Poetry, so it does contain the plugin's generated version. So in the generated source distribution, the plugin's version is already everywhere, and the plugin doesn't need to operate at all.

So my suggestion is to have an option that, when the version label in `pyproject.toml` is different from, say, '0.0.0', deactivates the plugin. Alternatively, the plugin could detect that a source distribution is being generated, and in that case remove itself from `pyproject.toml`. Or just change `enable` to `false`.

**Comment by mtkennerly** [comment]
Oh, I see now; thanks for clarifying. Yes, that should definitely be fixed. I'll look into this.

**Comment by mtkennerly** [comment]
This is now fixed in v0.12.3. I took your suggestion to set `enable` to `false` temporarily so that that gets set in the source distribution :+1:

**Comment by jhrmnn** [comment]
Excellent, thanks!

**Comment by arneyjfs** [comment]
### In docker builds - Make sure to copy across the `.git` directory into the container before build
Not sure where else to post this but in case someone arrives here having a painful experience building docker images with Poetry, Poetry dynamic versioning, and local (editable) installs, the answer for me was to copy across the `.git` directory into the container before build. It seems obvious once you realise it's dynamic versioning causing the problems, but at a high level it is not obvious why this would matter

**Comment by mtkennerly** [comment]
I've added a note to the Dunamai README about that: https://github.com/mtkennerly/dunamai/commit/cb28211e7da44f0333893229b5c642d534afed43 (which is linked from the poetry-dynamic-versioning README's "caveats" section)
