### ISSUE TITLE
Support for branch name

### ISSUE THREAD

**Issue by sl304227-nh** [mtkennerly/poetry-dynamic-versioning#56]
Not really an issue, but is there support for a branch name in the pattern?

For example:

In my feature branch, it would build like this:
`v1.0.0.my-branch`

After merging to develop, it would build like this:
`v1.0.0.develop`

After merging to master, it would build like this, dropping the suffix:
`v1.0.0`

Where `v1.0.0` could be set in the toml file, and the branch name would overwrite.

Any thoughts?

**Comment by mtkennerly** [comment]
I might be open to adding this, but I'd like to discuss your use case a bit more first. Why would builds for the same commit, on two different branches, need to be differentiated? If the commit is the same, I would expect the builds to be the same, and that's an assumption behind the design of the plugin and Dunamai.

There are some potential issues that may or may not affect your use case:

* Branch names with slashes (which are quite common) would be disallowed by PEP 440.
* PEP 440 would require this to be in the local segment (`v1.0.0+develop` rather than `v1.0.0.develop`).
* I'd prefer not to have special behavior for specific branch names by default, so to omit `master`, you'd need to write some logic in `format-jinja`, such as: `{%- if branch != 'master' -%}+{{ branch }}{%- endif -%}`

> Where `v1.0.0` could be set in the toml file, and the branch name would overwrite.

A design goal of the plugin is to avoid manually updating any version in pyproject.toml and maintain it by tags exclusively. You *could* hard-code a version base in `format` or `format-jinja`, but that would be a bit antithetical to the plugin.

**Comment by xtofl** [comment]
> Why would builds for the same commit, on two different branches, need to be differentiated?

That would only be an edge case.  During feature development, we ship multiple alpha's (or beta's) to testers.  It's more convenient to trace back the origin of the package if the branch name is in it.

**Comment by mtkennerly** [comment]
This will be included in the next release, within a day or two.
