### ISSUE TITLE
Accessing Package Version in CI/CD Pipeline

### ISSUE THREAD

**Issue by colby-vickerson** [mtkennerly/poetry-dynamic-versioning#60]
I have a python package that I deploy in a CI/CD pipeline and I only want to publish the package given a clean tag/version number. I have successfully done this before with the following:

```        
        pip3 install pipenv
        pipenv install --dev --python `which python3` --deploy --ignore-pipfile
        version=`pipenv run python setup.py --version`

        if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
        then
            echo "Publishing package version: $version"
            pipenv run python setup.py bdist_wheel upload
        else
          echo "Not a clean distribution, skipping release - Version: $version"
        fi
```
I use Pipenv to manage the package and want to switch over to Poetry, while taking advantage of poetry-dynamic-versioning. Do you have a recommended approach to get the version?

**Comment by mtkennerly** [comment]
Since the plugin uses Dunamai anyway, the simplest option would be to check if `dunamai from git --format '{distance}'` prints 0, which means the current commit has a version-like tag. If you have a custom `pattern` in pyproject.toml, you would just need to pass the same `--pattern`. You could print the full version this way as well, but just checking the distance would normally be enough.
