### ISSUE TITLE
Feature request: Command line flag to reset in-place changes

### ISSUE THREAD

**Issue by jamilraichouni** [mtkennerly/poetry-dynamic-versioning#66]
Hi,

First: Big thanks for this great plugin, I love it!

I have a use case where it would really make sense to be able to run `poetry-dynamic-versioning` from the command line and reset the modifications afterwards.

So what we already have is from the top-level README:

![image](https://user-images.githubusercontent.com/45113557/144407680-85053c72-79dc-4c26-81c4-2dd5494909ed.png)

Cool would be sth like a flag `--reset` that resets all value strings matching a pattern from `tool.poetry-dynamic-versioning.substitution.patterns` back to `0.0.0`.

All best and many thanks,
Jamil

**Comment by mtkennerly** [comment]
Sorry for the late reply! I hadn't added this before because I thought it would be enough to run `git checkout -- .` (or the equivalent for other version control systems), but once #62 is implemented, you could use that mechanism to do it (e.g., `POETRY_DYNAMIC_VERSIONING_BYPASS=0.0.0 poetry-dynamic-versioning`).
