### ISSUE TITLE
Does the plugin change the behavior of `poetry version` command?

### ISSUE THREAD

**Issue by josecelano** [mtkennerly/poetry-dynamic-versioning#67]
Hi,I have a question and I do not find the answer in the documentation.

If if run the command `poetry version` with the plugin disabled I get this output:

```
my-package 0.0.0
```

The way I disable it:

```
[tool.poetry-dynamic-versioning]
enable = false
vcs = "git"
```

and with the plugin enabled I get:

```
my-package 0.2.1.post3.dev0+10871b5
```

What I understand from the documentation is the behavior of Poetry is only changed when you use the `poetry build` command.

I've been reading the code and It seems the plugin overwrite the poetry instance [here](https://github.com/mtkennerly/poetry-dynamic-versioning/blob/4454e5082bf1fc2f4a39fa523a9b665eda5d638f/poetry_dynamic_versioning/__init__.py#L371-L372) in order to use the version from [Dunamai](https://github.com/mtkennerly/dunamai).

Is that right?

**Comment by mtkennerly** [comment]
Sorry for the late reply, but  yes, the plugin does takes effect when using `poetry version` as well, not just the build command. From the README (emphasis added):

> With the minimal configuration above, the plugin will automatically take effect when you run commands ***such as*** `poetry build`

We don't completely overwrite the `Poetry` class instance, but we do modify some of its internal values in order to set the version from Dunamai. Whenever Poetry instantiates that class (which should be during the handling of most, if not all, Poetry commands), the patched code will take effect.
