### ISSUE TITLE
Controlling dev/post specifiers

### ISSUE THREAD

**Issue by janheindejong** [mtkennerly/poetry-dynamic-versioning#7]
Nice plugin... works well. 

Is it possible to control when the post specifier and when the dev specifier are incremented? When I'm ahead by N commits from the last tag, I now get x.x.x.postN.dev0. I haven't found a way to get for instance x.x.x.postN, or x.x.x.post1.devN.

**Comment by mtkennerly** [comment]
Hello! It's not specifically configurable right now since I couldn't think of a use case for it, but if you have one, I'd be curious to know what it is. The `format` option technically supports it (example: `format: "{base}.post1.dev{distance}"`), but there's no option right now to specify different formats for tagged and untagged commits, which I think would be a good, generic way to support your use case, so I'll work on that.

**Comment by mtkennerly** [comment]
I just published v0.5.0 with a new option, `format-jinja`, to enable [Jinja templates](https://palletsprojects.com/p/jinja). Please try it out and let me know if it does everything you need:

```
format-jinja = "{% if distance == 0 %}{{ base }}{% else %}{{ base }}.post1.dev{{ distance }}{% endif %}"
```

**Comment by janheindejong** [comment]
The reason I was asking, is that it would feel more natural to use the dev specifier for the commit count, than the post specifier. 

I was thinking of this,  but realised it would work, since that would mean C2 and C3 would be recognized as _older_ that C1. 

C3; 0.1.dev2
|
C2; 0.1.dev1
|
C1, tag: v0.1; 0.1

However, this would be an option, although that would mean that the code should recognize the post specifier in the tag, and increment it. 

C5; 0.1.post2.dev1
|
C4, tag v0.1.post1; 0.1.post1
|
C3; 0.1.post1.dev2
|
C2; 0.1.post1.dev1
|
C1, tag: v0.1; 0.1

The current setup works for me, but it would inhibit me to actually release a post version, am I right?

**Comment by mtkennerly** [comment]
Yeah, the default behavior isn't really geared for releasing post-versions since it always seemed rare to me. That said, you can actually accomplish your second option by:

* Setting `pattern` so that it includes `.post\d+` in the `<base>` capture group
* Setting `format-jinja` to check for the presence of `.post` in `base`

This seems to work:

```toml
pattern = "^v(?P<base>\\d+\\.\\d+\\.\\d+(.post\\d+)?)(-?((?P<stage>[a-zA-Z]+)\\.?(?P<revision>\\d+)?))?$"
format-jinja = """
    {%- if distance == 0 -%}
        {{ base }}
    {%- else -%}
        {%- set base_pair = base.split('.post') -%}

        {%- if base_pair | length == 1 -%}
            {{ base }}.post1
        {%- else -%}
            {{ base_pair[0] }}.post{{ base_pair[1] | int + 1 }}
        {%- endif -%}

        .dev{{ distance }}
    {%- endif -%}
"""
```

On the commit after tag `0.5.0`, it produces `0.5.0.post1.dev1`, and on the commit after tag `9.9.9.post2`, it produces `9.9.9.post3.dev1`.
