### ISSUE TITLE
Feature request: Additional/alternate substitution rules.

### ISSUE THREAD

**Issue by MSLeiter** [mtkennerly/poetry-dynamic-versioning#74]
# Enhancement Request

A few additional possibilities for default substitution behavior.

I understand that one can specify a list of patterns (or directly specify the files to search) with the `files` property in the pyproject.toml `[tool.poetry-dynamic-versioning.substitution]` section. However, I believe a few other defaults locations should be checked, depending on other standard locations and/or how the project is configured.

## Concept 1 - rules to find more packages to search for substitution files

Search for the following, and if discovered, search for the default files (`__init__.py`, `__version__.py`, and `_version.py`) in the following locations:
1. If `src` folder is present in the root, search for the default files nested one level under `src`. For example, use pattern `src/*/__init__.py` to find `__init__.py` files in all packages starting one level under the standard `src` folder.
2. In the `[tool.poetry]` section, if `packages` is specified, look for the default files in each package. e.g. if packages is `[{ include = "mypackage", from ="lib" }]`, then search the `lib/mypackage` folder for the standard files. There can be multiple packages listed there.

However, on complex projects, you may not actually want to find all versions, as some of the dependent packages that are present (perhaps through submodules) may have their own separate version schemes.

## Concept 2: Specify the package locations where substitution should occur

1. Add a new property to the substitutions section of the pyproject.toml, called packages (default: None or empty list).
    - The packages list will have the relative path to all packages that should be searched for standard substitution files and symbols.  
    - e.g. `packages = ['src/mypackage']` will search in the folder src/mypackage from the repo root for files
 2. Add another new property called package_files which is the list of files to search for symbols (default: [`__init__.py`, `__version__.py`, `_version.py`])
 3. Use the existing "patterns" property for the list of regex patterns to use to find the symbols to substitute the version in.
 4. By default, if packages is set, do not search any other locations via default rules (such as the files property or rules in Concept 1), unless files property is also set.

## Other thoughts

Both of the above could be implemented. Main user value is:
1. having substitution work by default more often (Concept 1)
2. lower effort way to specify the exact folders to search with Concept 2, with less likelihood of typos and trying to understand what isn't working (entering just folders, rather than globs or regex).

**Comment by mtkennerly** [comment]
Thanks for this suggestion! The next release will provide a `folders` option (concept 2) to help streamline these use cases.

I've chosen not to implement concept 1 since `packages` can also be file paths/globs, not just folders. For example, in this snippet from the Poetry docs, it's not clear what should happen with `extra_package`  - would we ignore the `files`/`package_files` list and just inspect the included `*.py` files, would we drop the rest of the path after the initial folder name, or something else?

```toml
packages = [
    { include = "my_package" },
    { include = "extra_package/**/*.py" },
]
```

I think `folders` is easier to understand and is still pretty concise for common cases.

### Example 1
Config:

```toml
folders = [
    { path = "src" }
]
```

Matches:

* `./*.py`
* `./*/__init__.py`
* `./*/__version__.py`
* `./*/_version.py`
* `./src/*.py`
* `./src/*/__init__.py`
* `./src/*/__version__.py`
* `./src/*/_version.py`

### Example 2
Config:

```toml
folders = [
    { path = "docs", files = ["*.txt"], patterns = ["(<).*(>)"] }
]
```

Matches:

* `./*.py`
* `./*/__init__.py`
* `./*/__version__.py`
* `./*/_version.py`
* `./docs/*.txt`
