### ISSUE TITLE
Commit hash has one letter more on CI

### ISSUE THREAD

**Issue by rdbisme** [mtkennerly/poetry-dynamic-versioning#96]
Hello, 
running `poetry build -f wheel` on my local Windows machines generate this wheel `package-3.14.0.dev2+gbc054552-cp310-cp310-win_amd64.whl`. 

While on `python:slim` docker image, the wheel is `package-3.14.0.dev2+gbc05455-cp310-cp310-manylinux_2_24_x86_64.whl`

The windows wheel has the character `2` in addition to the commit hash. Any idea where this might come from? 

I'm using `poetry-dynamic-versioning 0.20.0`. 

Here the config: 
```toml
[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
dirty = "true"
format-jinja = """
    {%- if distance == 0 -%}
        {{ serialize_pep440(base, stage, revision) }}
    {%- elif revision is not none -%}
        {{ serialize_pep440(base, stage, revision + 1, dev=distance, metadata=["g" + commit]) }}
    {%- else -%}
        {{ serialize_pep440(bump_version(base, 1), stage, revision, dev=distance, metadata=["g" + commit]) }}
    {%- endif -%}
"""
```

**Comment by rdbisme** [comment]
Errata: I'm using the latest version compatible with `poetry 1.1.x` (0.17.1), if it makes a difference. Indeed, git version is different, I'll try to run the command in the shell and see if I see a difference.

**Comment by mtkennerly** [comment]
Nah, the plugin version wouldn't make a difference. The Git interfacing comes from Dunamai, and the way it gets the Git commit hasn't changed in a long time (back in Dunamai v0.7.0).

**Comment by rdbisme** [comment]
Thanks for helping. At the end I think the problem was the `auto` settings of `abbrev` config. It actually adapts the length to the size of the repo. So I followed your suggestion and used `full-commit` and jinja to fix the size.

One note: I has to strip the `commit` variable command because otherwise it would contain a `\n ` before and would make `poetry` fail. Not sure if it's intended or maybe fixed in following versions.

**Comment by mtkennerly** [comment]
Hmm, that's definitely not intended. I haven't seen that issue before, so not sure what difference would lead to the line break, but I can definitely add a safeguard for it. Once it's available, you could get the fix by updating Dunamai (a dependency of poetry-dynamic-versioning) without having to update the plugin itself (since you're still on Poetry 1.1.x).

**Comment by mtkennerly** [comment]
Hmm, that's definitely not intended, although I haven't seen it before in the tests. Could you share your updated `format-jinja` config? Just curious if the line break sneaked in there.

If not, I can definitely add a safeguard for it. Once it's available, you could get the fix by updating Dunamai (a dependency of poetry-dynamic-versioning) without having to update the plugin itself (since you're still on Poetry 1.1.x).

**Comment by rdbisme** [comment]
That was indeed it. 

This was the `jinja-template` for the context: 

```
format-jinja = """
    {% commit = commit[:8].strip() %}
    {%- if distance == 0 -%}
        {{ serialize_pep440(base, stage, revision) }}
    {%- elif revision is not none -%}
        {{ serialize_pep440(base, stage, revision + 1, dev=distance, metadata=["g" + commit]) }}
    {%- else -%}
        {{ serialize_pep440(bump_version(base, 1), stage, revision, dev=distance, metadata=["g" + commit]) }}
    {%- endif -%}
"""
```
